export const themes = {
  lightTheme: {
    type: "light",
    bodyBackground: "#e2e2e2",
    text: "#3D3D3DFF",
    linkColor: "#252525",
    buttonSubmit: "#4b8cc7",
    buttonReset: "#fff0c0",
    textContent: "#545454",
    container: "#fdfdfd",
    toggleBorder: "#b7b7b7",
    toggleText: "#b7b7b7",
    toggleHover: "#fdfdfd",
    separator: "#ebebeb",
    gradientYellow: "linear-gradient(90deg, #fcf7e5, #ffe0e0)",
    gradientGray: "linear-gradient(90deg, #fdfaf2, #cecece)",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.25)",
    grid: '"cards-grid__item_main cards-grid__item_main cards-grid__item_5"\n    "cards-grid__item_main cards-grid__item_main cards-grid__item_6"\n    "cards-grid__item_1 cards-grid__item_3 cards-grid__item_7"\n    "cards-grid__item_1 cards-grid__item_3 cards-grid__item_8"\n    "cards-grid__item_2 cards-grid__item_4 cards-grid__item_9"\n    "cards-grid__item_2 cards-grid__item_4 cards-grid__item_10"',
    gridColumns: "33.33% 33.33% auto",
  },
  darkTheme: {
    type: "dark",
    bodyBackground: "#2b2b2b",
    text: "#e5e5e5",
    linkColor: "#ffffff",
    buttonSubmit: "#78a4c7",
    buttonReset: "#93866a",
    textContent: "#a6a6a6",
    container: "#3c3f41",
    toggleBorder: "#939393",
    toggleText: "#676767",
    toggleHover: "#2b2b2b",
    separator: "#4d4d4d",
    gradientYellow: "linear-gradient(90deg, #343438, #625c50)",
    gradientGray: "linear-gradient(90deg, #313335, #676767)",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.7)",
    grid: '"cards-grid__item_5 cards-grid__item_main cards-grid__item_main"\n  "cards-grid__item_6 cards-grid__item_main cards-grid__item_main"\n  "cards-grid__item_7 cards-grid__item_1 cards-grid__item_3"\n  "cards-grid__item_8 cards-grid__item_1 cards-grid__item_3"\n  "cards-grid__item_9 cards-grid__item_2 cards-grid__item_4"\n  "cards-grid__item_10 cards-grid__item_2 cards-grid__item_4"',
    gridColumns: "auto 33.33% 33.33%",
  },
};
